#配置数据源
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:log4jdbc:mysql://localhost:3306/exec
    username: root
    password: 123456
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    hikari:
      max-lifetime: 180000
      maximum-pool-size: 10
      minimum-idle: 3


  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  #配置 Jpa
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true


  redis:
    #数据库索引
    database: 3
    host: 127.0.0.1
    port: 6379
    password:
    #连接超时时间
    timeout: 50000
#jwt
jwt:
  header: Authorization
  secret: nightmallSecret
  # token 过期时间/毫秒，6小时  1小时 = 3600000 毫秒
  expiration: 21600000
  # app token 过期时间/毫秒，30天 1000 * 60 * 60 * 24 * 30 = 2_592_000_000
  appExpiration: 2592000000
  # 在线用户key
  online: online-token
  # 验证码
  codeKey: code-key
  #短信验证码
  smsKey: sms-key

#log
logging:
  path: /var/log/exec/

  level:
    org:
      springframework:
        jdbc:
          core: TRACE

swagger:
  enabled: true
